version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: drf_blog
    volumes:
      - .:/drf_blog
    ports:
      - 8000:8000
    depends_on:
      - db
      - celery
    env_file:
      - ./.env
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    env_file:
      - ./.env
  celery:
    build: .
    volumes:
      - .:/store
    command: celery -A drf_blog worker -l info
    depends_on:
      - redis

volumes:
  postgres_data:
  redis-data: